server:
  port: 1234
  session:
    timeout: 1800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wee
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    minIdle: 10
    maxActive: 35
    connectionTimeout: 30000
    maxLifetime: 120000
    validationQuery: select 1
