server:
  port: 1234
  session:
    timeout: 1800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    minIdle: 10
    maxActive: 35
    connectionTimeout: 30000
    maxLifetime: 120000
    validationQuery: select 1
    connectionInitSql: set names utf8mb4
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    pool:
      max-idle: 1024
      max-wait: 1000
      min-idle: 100
